### ISSUE TITLE
Unable to send message. Check sender, recipients and message body

### ISSUE THREAD

**Issue by eshad** [mikechabot/smtp-email-spoofer-py#4]
smtp.gmail.com / smtp.googlemail.com : 587

finally it fails with 
Unable to send message. Check sender, recipients and message body
Error
Pls find a fix for it..

**Comment by Antoineriendepluscommun** [comment]
Same issue her when trying with norepy@netflix.com

**Comment by altendky** [comment]
A nice server doesn't want to get blacklisted by allowing address spoofing/spam.  That'd be my guess as to the problem.

**Comment by eshad** [comment]
Use msmtp to start private mail server @ localhost
Config and start using msmtpd & 
then u can send it with localhost script need little modifications only.. for none auth option ise update ssl cer. 
Good luck!

**Comment by altendky** [comment]
Can't you just use any client then?  Not that I'm sure what this does beyond a generic client.
