### ISSUE TITLE
No module named spoofer

### ISSUE THREAD

**Issue by Brsk79** [mikechabot/smtp-email-spoofer-py#5]
Can't launch spoof.py because I get an error on startup.
Already installed requirements, any help?

**Comment by guberti** [comment]
It's likely you're running the project with Python 2.X instead of Python 3 (Python 3 changes the way imports are handled)

**Comment by Brsk79** [comment]
Idk, I tried on a freshly installed OS with python3 and it got past this issue.
So maybe you guessed right.
